### ISSUE TITLE
Java8u40 Can not copy a non-root Method

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-loaded#108] opened 2015-03-04 13:20 UTC
Raised on Twitter:

looks like #Spring doesn't like Java8u40
"Can not copy a non-root Method 
ERROR org.springsource.loaded.jvm.JVM - ... Incompatible JVM?"

**Comment by Dierk** [comment] 2015-03-04 13:31
Here is the stack trace

Caused by: java.lang.IllegalArgumentException: Can not copy a non-root Method
	at java.lang.reflect.Method.copy(Method.java:151) ~[na:1.8.0_40]
	... 59 common frames omitted
ERROR org.springsource.loaded.jvm.JVM - Problems copying method. Incompatible JVM?
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.springsource.loaded.jvm.JVM.copyMethod(JVM.java:134) ~[springloaded-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springsource.loaded.ri.OriginalClassInvoker.createJavaMethod(OriginalClassInvoker.java:68) [springloaded-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlClassGetDeclaredMethods(ReflectiveInterceptor.java:151) [springloaded-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.grails.core.util.ClassPropertyFetcher.init(ClassPropertyFetcher.java:185) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at org.grails.core.util.ClassPropertyFetcher.<init>(ClassPropertyFetcher.java:95) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:86) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:61) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at org.grails.core.AbstractGrailsClass.<init>(AbstractGrailsClass.java:91) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at org.grails.core.DefaultGrailsDomainClass.<init>(DefaultGrailsDomainClass.java:79) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at org.grails.core.artefact.DomainClassArtefactHandler.newArtefactClass(DomainClassArtefactHandler.java:62) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:784) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:480) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.core.DefaultGrailsApplication.configureLoadedClasses(DefaultGrailsApplication.java:245) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.core.DefaultGrailsApplication.initialise(DefaultGrailsApplication.java:687) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.boot.config.GrailsApplicationPostProcessor.performGrailsInitializationSequence(GrailsApplicationPostProcessor.groovy:97) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.boot.config.GrailsApplicationPostProcessor.initializeGrailsApplication(GrailsApplicationPostProcessor.groovy:88) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.boot.config.GrailsApplicationPostProcessor.<init>(GrailsApplicationPostProcessor.groovy:76) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.groovy:36) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at irixserver.Application.grailsApplicationPostProcessor(Application.groovy) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270) [springloaded-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1111) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1006) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:116) [spring-context-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:606) [spring-context-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462) [spring-context-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) [spring-boot-1.2.1.RELEASE.jar:1.2.1.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:43) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:207) [grails-core-3.0.0.M2.jar:3.0.0.M2]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:196) [grails-core-3.0.0.M2.jar:3.0.0.M2]
Build cancelled.

**Comment by wmacgyver** [comment] 2015-03-05 17:18
apparently this was already reported back in Jan 10 :(  #98

**Comment by aclement** [comment] 2015-03-05 19:16
I had a go at fixing it, see further comments in #98

**Comment by aclement** [comment] 2015-03-13 15:25
believed fixed in 1.2.2.

**Closed by aclement** 2015-03-13 15:25 UTC
